/**
 * @file calcDerivs.cuh
 * @brief Declares the function for calculating the derivatives of the position/velocity 
 *  for all bodies in an N-body system. A declaration for a function used to compute a 
 *  softened gravitational radius is also included in this header file.
 *
 * Project originally by:
 * [Original Author Name]
 *
 * Modified by:
 * Steven McKelvey - Calvin University, January 2025
 *
 * NOTE: This project's function documentation was generated by ChatGPT on August 22nd, 2024.
 *          Keep in mind that there may be errors and the documentation may not be 100% accurate.
 */

#include <stdlib.h>
#include <stddef.h>
#include "nbody.cuh"

#ifndef CALCDERIVS
#define CALCDERIVS

void calcDerivs(double *x, double *derivs, double t, double tStep,
                NbodyModel *theModel);
double computeSoftenedRadius(double g_m, double tstep);

#endif