/**
 * @file nbody.cuh
 * @brief Defines the NbodyModel structure and functions for simulating an N-body gravitational system.
 *
 * This header file provides the definition of the `NbodyModel` structure, which is used to represent
 * a system of bodies under the influence of gravitational forces. The file also declares functions 
 * for allocating and initializing the model, setting parameters such as mass and scale, and performing 
 * various operations on the model like spinning and speeding up the bodies.
 *
 * Project originally by:
 * David Joiner
 *
 * Modified by:
 * Steven McKelvey - Calvin University, January 2025
 *
 * NOTE: This project's function documentation was generated by ChatGPT on August 22nd, 2024.
 *          Keep in mind that there may be errors and the documentation may not be 100% accurate.
 */

#ifndef NBODY
#define NBODY

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#define PI 3.14159

/**
 * @struct NbodyModel
 * @brief Represents the state of an N-body gravitational system.
 *
 * This structure holds all the necessary information to simulate an N-body system, including the number of bodies, 
 * their masses, positions, velocities, and other parameters like the gravitational constant and time step.
 *
 * NOTE: XPRIME2 is used for the Improved Euler and RK4 functions in stepModel.c
 *          XPRIME3 and XPRIME4 are used for the RK4 function. 
 */
typedef struct
{
    int num_bodies;         /**< Number of bodies in the system. */
    double *mass;           /**< Array of masses for each body. */
    double default_mass;    /**< Default mass for bodies if not specified. */
    double default_scale;   /**< Default scale for spatial calculations. */
    double default_G;       /**< Default gravitational constant. */
    double *x;              /**< Array of x-coordinates of each body. */
    double *y;              /**< Array of y-coordinates of each body. */
    double *z;              /**< Array of z-coordinates of each body. */
    double *vx;             /**< Array of x-components of velocity for each body. */
    double *vy;             /**< Array of y-components of velocity for each body. */
    double *vz;             /**< Array of z-components of velocity for each body. */
    double *X;              /**< Temporary array for integration calculations. */
    double *X2;             /**< Temporary array for integration calculations. */
    double *XPRIME;         /**< Temporary array for integration calculations. */
    double *XPRIME2;        /**< Temporary array for integration calculations. */
    double *XPRIME3;        /**< Temporary array for integration calculations. */
    double *XPRIME4;        /**< Temporary array for integration calculations. */
    double G;               /**< Gravitational constant for the simulation. */
    double t;               /**< Current time in the simulation. */
    int iteration;          /**< Current iteration number of the simulation. */
} NbodyModel;

NbodyModel *allocateNbodyModel(int num_bodies);
void setDefaultsNbodyModel(NbodyModel *theModel);
void setMassNbodyModel(NbodyModel *theModel, double mass);
void setScaleNbodyModel(NbodyModel *theModel, double scale);
void setGNbodyModel(NbodyModel *theModel, double G);
int initializeNbodyModel(NbodyModel *theModel);
int freeNbodyModel(NbodyModel *theModel);
void spinNbodyModel(NbodyModel *theModel, double rotFactor);
void speedNbodyModel(NbodyModel *theModel, double v);

#endif
