/**
 * @file galaxsee.cpp
 * @brief Includes the main function for running the N-body simulation
 *
 * This file includes a main function that:
 * - Defines the initial conditions for the simulation
 * - Reads the command line arguments given by the user
 * - Runs the simulation
 * - Outputs the results
 *
 * Project originally by:
 * [Original Author Name]
 *
 * Modified by:
 * Steven McKelvey - Calvin University, January 2025
 *
 * NOTE: This project's function documentation was generated by ChatGPT on August 22nd, 2024.
 *          Keep in mind that there may be errors and the documentation may not be 100% accurate.
 */

#include "Simulator.hpp"
#include "graphics.hpp"
#include <time.h>

int main(int argc, char **argv) {
    int num_bodies = 500;        // Default number of bodies in the simulation
    double tStep = 8.0;          // Time step for each simulation iteration (1.0 by default)
    double tFinal = 20000.0;      // Final simulation time (1000.0 by default)
    int count_updates = 0;       // Counter for simulation updates
    int skip_updates = 1;        // Controls how often the display updates
    int show_display = 1;        // Flag to control whether to show the display
    double rotation_factor = 1.0;// Factor influencing the rotational velocity of bodies
    double initial_v = 0.0;      // Initial velocity for bodies
    time_t begin;                // Time at the start of the simulation
    time_t end;                  // Time at the end of the simulation

    time(&begin); // Record the start time

    // Command line argument parsing
    printf("USAGE: program_name num_bodies t_final rotation_factor initial_v show_display\n");
    int i = 0;
    if (argc > ++i) {
        sscanf(argv[i], "%d", &num_bodies);
    }
    if (argc > ++i) {
        sscanf(argv[i], "%lf", &tFinal);
    }
    if (argc > ++i) {
        sscanf(argv[i], "%lf", &rotation_factor);
    }
    if (argc > ++i) {
        sscanf(argv[i], "%lf", &initial_v);
    }
    if (argc > ++i) {
        sscanf(argv[i], "%d", &show_display);
    }

    // Display the model summary
    printf("Model Summary\n");
    printf("num_bodies = %d\n", num_bodies);
    printf("tFinal = %lf\n", tFinal);
    printf("rotation_factor = %lf\n", rotation_factor);
    printf("initial_v = %lf\n", initial_v);

    // Initialize the N-body model
    Simulator galaxySim(num_bodies, rotation_factor, initial_v, tFinal, tStep,
                        count_updates, skip_updates, show_display);
    // run the main simulation loop
    galaxySim.run();

    time(&end); // Record the end time

    // Display the elapsed wall time for the simulation
    printf("Wall Time Elapsed = %8.lf seconds\n", difftime(end, begin));

    // Pause the program so the user can view the final output
    // https://stackoverflow.com/questions/9386651/pause-screen-at-program-completion-in-c
    printf("Press any key to continue...\n");
    getchar(); // Wait for user input before closing

    return 0;
}