/**
 * @file graphics.hpp
 * @brief Declares the functions for displaying an X11 render of the simulation.
 *
 * This file provides the declaration of functions for initializing an X11 window and
 * updating the window based on the simulation's current state.
 *
 * Project originally by:
 * David Joiner
 *
 * Modified by:
 * Steven McKelvey - Calvin University, January 2025
 *
 * NOTE: This project's function documentation was generated by ChatGPT on August 22nd, 2024.
 *          Keep in mind that there may be errors and the documentation may not be 100% accurate.
 */

#ifndef GRAPHICS
#define GRAPHICS

#include "nbody.hpp"
#include "display.hpp"
#include <X11/Xlib.h>
#include <assert.h>
#include <unistd.h>
#define NIL (0)

int updateNbodyModel(NbodyModel *theModel);

#endif