/**
 * @file nbody.hpp
 * @brief Defines the NbodyModel structure and functions for simulating an N-body gravitational system.
 *
 * This header file provides the definition of the `NbodyModel` structure, which is used to represent
 * a system of bodies under the influence of gravitational forces. The file also declares functions 
 * for allocating and initializing the model, setting parameters such as mass and scale, and performing 
 * various operations on the model like spinning and speeding up the bodies.
 *
 * Project originally by:
 * David Joiner
 *
 * Modified by:
 * Steven McKelvey - Calvin University, January 2025
 *
 * NOTE: This project's function documentation was generated by ChatGPT on August 22nd, 2024.
 *          Keep in mind that there may be errors and the documentation may not be 100% accurate.
 */

#ifndef NBODY
#define NBODY

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <mpi.h>

#define PI 3.14159

class NbodyModel
{
public:
    NbodyModel() : num_bodies(0) {}
    NbodyModel(unsigned numBodies);
    int initializeNbodyModel();
    ~NbodyModel();
    void setDefaultsNbodyModel();
    void setMassNbodyModel(double mass);
    void setScaleNbodyModel(double scale);
    void setGNbodyModel(double G);
    void speedNbodyModel(double v);
    void spinNbodyModel(double rotFactor);
    int stepNbodyModel(double tStep);
    
    
    void calcDerivs(double *x, double *derivs, double t, double tStep);

    unsigned num_bodies;    /**< Number of bodies in the system. */
    double *mass;           /**< Array of masses for each body. */
    double default_mass;    /**< Default mass for bodies if not specified. */
    double default_scale;   /**< Default scale for spatial calculations. */
    double default_G;       /**< Default gravitational constant. */
    double *x;              /**< Array of x-coordinates of each body. */
    double *y;              /**< Array of y-coordinates of each body. */
    double *z;              /**< Array of z-coordinates of each body. */
    double *vx;             /**< Array of x-components of velocity for each body. */
    double *vy;             /**< Array of y-components of velocity for each body. */
    double *vz;             /**< Array of z-components of velocity for each body. */
    double *X;              /**< Temporary array for integration calculations. */
    double *X2;             /**< Temporary array for integration calculations. */
    double *XPRIME;         /**< Temporary array for integration calculations. */
    double *XPRIME2;        /**< Temporary array for integration calculations. */
    double *XPRIME3;        /**< Temporary array for integration calculations. */
    double *XPRIME4;        /**< Temporary array for integration calculations. */
    double G;               /**< Gravitational constant for the simulation. */
    double t;               /**< Current time in the simulation. */
    unsigned iteration;     /**< Current iteration number of the simulation. */

private:
    int stepNbodyModelEuler(double tStep);
    int stepNbodyModelIEuler(double tStep);
    int stepNbodyModelMPEuler(double tStep);
    int stepNbodyModelRK4(double tStep);
    double computeSoftenedRadius(double g_m, double tstep);
};

#endif
