/**
 * @file stepModel.h
 * @brief Declares the functions for updating the state of the N-body model by one iteration.
 *
 * This file provides the declaration for a general function for updating the 
 * state of the model, along with four other functions that provide 
 * different integration methods that the simulation can use.
 *
 * Project originally by:
 * [Original Author Name]
 *
 * Modified by:
 * Steven McKelvey - Calvin University, August 2024
 *
 * NOTE: This project's function documentation was generated by ChatGPT on August 22nd, 2024.
 *          Keep in mind that there may be errors and the documentation may not be 100% accurate.
 */
 
#ifndef STEPMODEL
#define STEPMODEL

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "calcDerivs.h"

#define PI 3.14159

int stepNbodyModel(NbodyModel *theModel, double tStep);
int stepNbodyModelEuler(NbodyModel *theModel, double tStep);
int stepNbodyModelIEuler(NbodyModel *theModel, double tStep);
int stepNbodyModelMPEuler(NbodyModel *theModel, double tStep);
int stepNbodyModelRK4(NbodyModel *theModel, double tStep);

#endif